backend:
  name: github
  repo: pbrandone/next-cms-test
  branch: master # Branch to update

publish_mode: editorial_workflow
media_folder: "static/images/"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about.json"
        extension: "json"
        fields:
          - {label: "Page title", name: "title", widget: "string"}
      - label: "Homepage"
        name: "homepage"
        file: "content/home.json"
        extension: "json"
        fields:
          - {label: "Page title", name: "title", widget: "string"}
          - {label: "Paragraph", name: "text", widget: "string"}
          - {label: "Featured Image", name: "image", widget: "image"}